apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "questionnaire.fullname" . }}-data-protection
  labels:
    {{- include "questionnaire.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.dataProtection.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.dataProtection.size | quote }}
